/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.BibliografiaDao;
import dao.CursoDao;
import dao.DisciplinaDao;
import entity.Bibliografia;
import entity.Curso;
import entity.Disciplina;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class CadastroBibliografia extends javax.swing.JDialog {


    boolean novo = true;
    String tituloAntigo;
    public CadastroBibliografia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jListaCursos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jListaDisciplinas = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jIsbn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jEditora = new javax.swing.JTextField();
        jSalvar = new javax.swing.JButton();
        jSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Curso");

        jLabel2.setText("Disciplina");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Referência Bibliográfica"));

        jLabel3.setText("Título");

        jLabel4.setText("Autor");

        jLabel5.setText("ISBN");

        jLabel6.setText("Ano");

        jLabel7.setText("Editora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEditora))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jAutor))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSalvar.setText("Salvar");
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });

        jSair.setText("Sair");
        jSair.setToolTipText("");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jListaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jListaDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSalvar)
                        .addGap(28, 28, 28)
                        .addComponent(jSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jListaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jListaDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalvar)
                    .addComponent(jSair))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (novo){
           listaCursos();
           listaDisciplinas();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
        boolean dadosValidos=true;
        
        if(jListaCursos.getSelectedItem().equals("Selecione")){
            JOptionPane.showMessageDialog(this, "Selecione o Curso", "Curso não selecionado", JOptionPane.WARNING_MESSAGE);
            dadosValidos=false;
        }
        
        if(jListaDisciplinas.getSelectedItem().equals("Selecione")){
            JOptionPane.showMessageDialog(this, "Selecione a Disciplina", "Disciplina não selecionada", JOptionPane.WARNING_MESSAGE);
            dadosValidos=false;
        }
        
        if (jTitulo.getText().isEmpty() || jAutor.getText().isEmpty() || jIsbn.getText().isEmpty() || 
            jAno.getText().isEmpty() || jEditora.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Preencha todos os campos", "Preenchimento incompleto", JOptionPane.WARNING_MESSAGE);
            dadosValidos=false;
        }
        
        if(dadosValidos){
            //Recupera o id do curso
            CursoDao cursoDao= new CursoDao();
            int idCurso= cursoDao.getIdCurso(jListaCursos.getSelectedItem().toString());
            
            DisciplinaDao disciplinaDao = new DisciplinaDao();
            int idDisciplina = disciplinaDao.getIdDisciplina(jListaDisciplinas.getSelectedItem().toString());
            
            Bibliografia bibliografia = new Bibliografia();
            bibliografia.setTitulo(jTitulo.getText());
            bibliografia.setAutor(jAutor.getText());
            bibliografia.setIsbn(jIsbn.getText());
            bibliografia.setAno(jAno.getText());
            bibliografia.setEditora(jEditora.getText());
            
            BibliografiaDao bibliografiaDao = new BibliografiaDao();
            //Código executado caso seja um novo registro
            if (novo){
                if(bibliografiaDao.Insere(idCurso, idDisciplina, bibliografia)){
                    JOptionPane.showMessageDialog(this, "Bibliografia cadastrada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar a bibliografia", "Erro", JOptionPane.WARNING_MESSAGE);
                }
            //Código executado quando se está atualizando um registro existente    
            }else{
                int idBibliografia = bibliografiaDao.getIdBibliografia(tituloAntigo);
                
                if(bibliografiaDao.Altera(idBibliografia, idCurso, idDisciplina, bibliografia)){
                    JOptionPane.showMessageDialog(this, "Bibliografia alterada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }else{
                     JOptionPane.showMessageDialog(this, "Erro ao alterar a bibliografia", "Erro", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jSalvarActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        dispose();
    }//GEN-LAST:event_jSairActionPerformed
    
    public void listaCursos(){
        CursoDao cursoDao = new CursoDao();
        List<Curso> listaCurso = cursoDao.getCursos();
        
        jListaCursos.removeAllItems();
        jListaCursos.addItem("Selecione");
        for (int i = 0; i < listaCurso.size(); i++) {
            jListaCursos.addItem(listaCurso.get(i).getDenominacao());
        }
    }
    public void listaDisciplinas(){
        DisciplinaDao disciplinaDao = new DisciplinaDao();
        List<Disciplina> listaDisciplina = disciplinaDao.getDisciplinas();
        
        jListaDisciplinas.removeAllItems();
        jListaDisciplinas.addItem("Selecione");
        for (int i = 0; i < listaDisciplina.size(); i++) {
            jListaDisciplinas.addItem(listaDisciplina.get(i).getNome());
        }
    }
    
    public void alteraBibliografia(String titulo){
        BibliografiaDao bibliografiaDao = new BibliografiaDao();
        Bibliografia bibliografia = new Bibliografia();
        CursoDao cursoDao = new CursoDao();
        DisciplinaDao disciplinaDao = new DisciplinaDao();
        
        bibliografia= bibliografiaDao.getBibliografia(bibliografiaDao.getIdBibliografia(titulo));
        
        if(!bibliografia.getTitulo().isEmpty()){
            listaCursos();
            listaDisciplinas();
            
            //Preenche o combobox curso
            Curso curso = cursoDao.getCurso(bibliografia.getFk_id_curso());
            jListaCursos.setSelectedItem(curso.getDenominacao());
            
            //Preenche o combobox disciplina
            Disciplina disciplina = disciplinaDao.getNomeDisciplina(bibliografia.getFk_id_disciplina());
            jListaDisciplinas.setSelectedItem(disciplina.getNome());
            
            //Preenche os campos de texto
            jTitulo.setText(bibliografia.getTitulo());
            jAutor.setText(bibliografia.getAutor());
            jIsbn.setText(bibliografia.getIsbn());
            jAno.setText(bibliografia.getAno());
            jEditora.setText(bibliografia.getEditora());
            
            //Atribui o valor do identificador recuperado da base de dados à váriavel identificadorAntigo, utilizada ao salvar a alteração
            tituloAntigo=jTitulo.getText();
                       
            novo=false;
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao buscar a bibliografia");
        }
    }
    public void consultaBibliografia(String titulo){
        BibliografiaDao bibliografiaDao = new BibliografiaDao();
        Bibliografia bibliografia = new Bibliografia();
        CursoDao cursoDao = new CursoDao();
        DisciplinaDao disciplinaDao = new DisciplinaDao();
        
        bibliografia= bibliografiaDao.getBibliografia(bibliografiaDao.getIdBibliografia(titulo));
        
        if(!bibliografia.getTitulo().isEmpty()){
            listaCursos();
            listaDisciplinas();
            
            //Preenche o combobox curso
            Curso curso = cursoDao.getCurso(bibliografia.getFk_id_curso());
            jListaCursos.setSelectedItem(curso.getDenominacao());
            
            //Preenche o combobox disciplina
            Disciplina disciplina = disciplinaDao.getNomeDisciplina(bibliografia.getFk_id_disciplina());
            jListaDisciplinas.setSelectedItem(disciplina.getNome());
            
            //Preenche os campos de texto
            jTitulo.setText(bibliografia.getTitulo());
            jAutor.setText(bibliografia.getAutor());
            jIsbn.setText(bibliografia.getIsbn());
            jAno.setText(bibliografia.getAno());
            jEditora.setText(bibliografia.getEditora());
            
            jSalvar.setEnabled(false);
            jListaCursos.setEnabled(false);
            jListaDisciplinas.setEnabled(false);
            
                       
            novo=false;
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao buscar a bibliografia");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroBibliografia dialog = new CadastroBibliografia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAno;
    private javax.swing.JTextField jAutor;
    private javax.swing.JTextField jEditora;
    private javax.swing.JTextField jIsbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jListaCursos;
    private javax.swing.JComboBox<String> jListaDisciplinas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSair;
    private javax.swing.JButton jSalvar;
    private javax.swing.JTextField jTitulo;
    // End of variables declaration//GEN-END:variables
}
