/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CursoDao;
import dao.PPCDao;
import entity.Curso;
import entity.PPC;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class CadastroPPC extends javax.swing.JDialog {
    boolean novo=true;
    String identificadorAntigo;
    /**
     * Creates new form CadastroPPC
     */
    public CadastroPPC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jListaCursos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPerfilCurso = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPerfilEgresso = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jFormaAcessoCurso = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jRepresentaçãoPerfilFormação = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jSistemaAvaliacaoProcessoEnsino = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jSistemaAvaliacaoProjetoCurso = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTrabalhoConclusaoCurso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jEstagioCurricular = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPoliticaAtendimentoDeficientes = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jSalvar = new javax.swing.JButton();
        jSair = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jIdentificador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Cursos");

        jLabel2.setText("Perfil Curso");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPerfilCurso.setColumns(20);
        jPerfilCurso.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jPerfilCurso.setLineWrap(true);
        jPerfilCurso.setRows(3);
        jPerfilCurso.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jPerfilCurso);

        jLabel3.setText("Perfil do Egresso");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPerfilEgresso.setColumns(20);
        jPerfilEgresso.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jPerfilEgresso.setLineWrap(true);
        jPerfilEgresso.setRows(3);
        jPerfilEgresso.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jPerfilEgresso);

        jLabel4.setText("Forma de Acesso Curso");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jFormaAcessoCurso.setColumns(20);
        jFormaAcessoCurso.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jFormaAcessoCurso.setLineWrap(true);
        jFormaAcessoCurso.setRows(3);
        jFormaAcessoCurso.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jFormaAcessoCurso);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jRepresentaçãoPerfilFormação.setColumns(20);
        jRepresentaçãoPerfilFormação.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jRepresentaçãoPerfilFormação.setLineWrap(true);
        jRepresentaçãoPerfilFormação.setRows(3);
        jRepresentaçãoPerfilFormação.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jRepresentaçãoPerfilFormação);

        jLabel5.setText("Representação Gráfica de um Perfil de Formação");

        jLabel6.setText("Sistema de Avaliação do Processo Ensino Aprendizagem");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jSistemaAvaliacaoProcessoEnsino.setColumns(20);
        jSistemaAvaliacaoProcessoEnsino.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jSistemaAvaliacaoProcessoEnsino.setLineWrap(true);
        jSistemaAvaliacaoProcessoEnsino.setRows(3);
        jSistemaAvaliacaoProcessoEnsino.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jSistemaAvaliacaoProcessoEnsino);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jSistemaAvaliacaoProjetoCurso.setColumns(20);
        jSistemaAvaliacaoProjetoCurso.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jSistemaAvaliacaoProjetoCurso.setLineWrap(true);
        jSistemaAvaliacaoProjetoCurso.setRows(3);
        jSistemaAvaliacaoProjetoCurso.setWrapStyleWord(true);
        jScrollPane6.setViewportView(jSistemaAvaliacaoProjetoCurso);

        jLabel7.setText("Sistema de Avaliação do Projeto do Curso");

        jLabel8.setText("Trabalho de Conclusao do Curso");

        jLabel9.setText("Estágio Currícular");

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPoliticaAtendimentoDeficientes.setColumns(20);
        jPoliticaAtendimentoDeficientes.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jPoliticaAtendimentoDeficientes.setLineWrap(true);
        jPoliticaAtendimentoDeficientes.setRows(3);
        jPoliticaAtendimentoDeficientes.setWrapStyleWord(true);
        jScrollPane7.setViewportView(jPoliticaAtendimentoDeficientes);

        jLabel10.setText("Política de Atendimendo à pessoas com Deficiência e/ou mobilidade reduzida");

        jSalvar.setText("Salvar");
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });

        jLabel11.setText("Identificador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTrabalhoConclusaoCurso))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jEstagioCurricular, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel10)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jListaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jListaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTrabalhoConclusaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEstagioCurricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalvar)
                    .addComponent(jSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (novo){
            ListaCursos();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
       boolean dadosValidos=true;
       
       //Verifica se o curso foi selecionado
        if(jListaCursos.getSelectedItem().equals("Selecione")){
            JOptionPane.showMessageDialog(this, "Selecione um curso!");
            dadosValidos=false;
        }
        
        //Verifica se todos os campos foram preenchidos
        if(jIdentificador.getText().isEmpty() || jPerfilCurso.getText().isEmpty() || jPerfilEgresso.getText().isEmpty() ||
        jFormaAcessoCurso.getText().isEmpty() || jRepresentaçãoPerfilFormação.getText().isEmpty() || jSistemaAvaliacaoProcessoEnsino.getText().isEmpty() ||
        jSistemaAvaliacaoProjetoCurso.getText().isEmpty() || jTrabalhoConclusaoCurso.getText().isEmpty() || 
        jEstagioCurricular.getText().isEmpty() || jPoliticaAtendimentoDeficientes.getText().isEmpty()){
            dadosValidos=false;
        }
        
        if (dadosValidos){
            PPCDao ppcDAO = new PPCDao();
            CursoDao cursoDao = new CursoDao();

            int idCurso = cursoDao.getIdCurso(jListaCursos.getSelectedItem().toString());

            PPC ppc = new PPC();

            ppc.setIdentificador(jIdentificador.getText());
            ppc.setPerfilCurso(jPerfilCurso.getText());
            ppc.setPerfilEgresso(jPerfilEgresso.getText());
            ppc.setFormaAcessoCurso(jFormaAcessoCurso.getText());
            ppc.setRepresentacaoPerfilFormacao(jRepresentaçãoPerfilFormação.getText());
            ppc.setSistemaAvaliacaoProcessoEnsinoAprendizagem(jSistemaAvaliacaoProcessoEnsino.getText());
            ppc.setSistemaAvaliacaoProjetoCurso(jSistemaAvaliacaoProjetoCurso.getText());
            ppc.setTrabalhoConclusaoCurso(jTrabalhoConclusaoCurso.getText());
            ppc.setEstagioCurricular(jEstagioCurricular.getText());
            ppc.setPoliticaAtendimentoDeficientes(jPoliticaAtendimentoDeficientes.getText());
            
            if(novo){
                //Código executado caso seja um novo cadastro
                if(ppcDAO.Insere(idCurso, ppc)){
                    JOptionPane.showMessageDialog(this, "PPC cadastrado com sucesso");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar o PPC");
                }
                    
            }else{
                //Caso seja alteração de um cadastro existente
                int idPPC = ppcDAO.getIdPPC(identificadorAntigo);
                    if(ppcDAO.Altera(idPPC, idCurso, ppc)){
                    JOptionPane.showMessageDialog(this, "PPC alterado com sucesso");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao alterar o PPC");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_jSalvarActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        dispose();
    }//GEN-LAST:event_jSairActionPerformed
    public void ListaCursos(){
        CursoDao cursoDao = new CursoDao();
        List<Curso> listaCurso = cursoDao.getCursos();
        
        jListaCursos.removeAllItems();
        jListaCursos.addItem("Selecione");
        for (int i = 0; i < listaCurso.size(); i++) {
            jListaCursos.addItem(listaCurso.get(i).getDenominacao());
        }
    }
    public void AlteraPPC(String identificador){
        
        PPCDao ppcDao = new PPCDao();
        CursoDao cursoDao = new CursoDao();

        PPC ppc = ppcDao.getPPC(ppcDao.getIdPPC(identificador));
        
        if(!ppc.getIdentificador().isEmpty()){
            ListaCursos();
            
            //Preenche o combobox curso
            Curso curso = cursoDao.getCurso(ppc.getFk_id_curso());
            jListaCursos.setSelectedItem(curso.getDenominacao());
            
            
            //Preenche os campos de texto
            jIdentificador.setText(ppc.getIdentificador());
            jPerfilCurso.setText(ppc.getPerfilCurso());
            jPerfilEgresso.setText(ppc.getPerfilEgresso());
            jFormaAcessoCurso.setText(ppc.getFormaAcessoCurso());
            jRepresentaçãoPerfilFormação.setText(ppc.getRepresentacaoPerfilFormacao());
            jSistemaAvaliacaoProcessoEnsino.setText(ppc.getSistemaAvaliacaoProcessoEnsinoAprendizagem());
            jSistemaAvaliacaoProjetoCurso.setText(ppc.getSistemaAvaliacaoProjetoCurso());
            jTrabalhoConclusaoCurso.setText(ppc.getTrabalhoConclusaoCurso());
            jEstagioCurricular.setText(ppc.getEstagioCurricular());
            jPoliticaAtendimentoDeficientes.setText(ppc.getPoliticaAtendimentoDeficientes());

            //Atribui o valor do identificador recuperado da base de dados à váriavel identificadorAntigo, utilizada ao salvar a alteração
            identificadorAntigo=jIdentificador.getText();
                       
            novo=false;
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao buscar o PPC");
        }
    }
    
        public void ConsultaPPC(String identificador){
        
        PPCDao ppcDao = new PPCDao();
        CursoDao cursoDao = new CursoDao();

        PPC ppc = ppcDao.getPPC(ppcDao.getIdPPC(identificador));
        
        if(!ppc.getIdentificador().isEmpty()){
            ListaCursos();
            
            //Preenche o combobox curso
            Curso curso = cursoDao.getCurso(ppc.getFk_id_curso());
            jListaCursos.setSelectedItem(curso.getDenominacao());
            
            
            //Preenche os campos de texto
            jIdentificador.setText(ppc.getIdentificador());
            jPerfilCurso.setText(ppc.getPerfilCurso());
            jPerfilEgresso.setText(ppc.getPerfilEgresso());
            jFormaAcessoCurso.setText(ppc.getFormaAcessoCurso());
            jRepresentaçãoPerfilFormação.setText(ppc.getRepresentacaoPerfilFormacao());
            jSistemaAvaliacaoProcessoEnsino.setText(ppc.getSistemaAvaliacaoProcessoEnsinoAprendizagem());
            jSistemaAvaliacaoProjetoCurso.setText(ppc.getSistemaAvaliacaoProjetoCurso());
            jTrabalhoConclusaoCurso.setText(ppc.getTrabalhoConclusaoCurso());
            jEstagioCurricular.setText(ppc.getEstagioCurricular());
            jPoliticaAtendimentoDeficientes.setText(ppc.getPoliticaAtendimentoDeficientes());
            
            jSalvar.setEnabled(false);
            jListaCursos.setEnabled(false);
                       
            novo=false;
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao buscar o PPC");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroPPC dialog = new CadastroPPC(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jEstagioCurricular;
    private javax.swing.JTextArea jFormaAcessoCurso;
    private javax.swing.JTextField jIdentificador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jListaCursos;
    private javax.swing.JTextArea jPerfilCurso;
    private javax.swing.JTextArea jPerfilEgresso;
    private javax.swing.JTextArea jPoliticaAtendimentoDeficientes;
    private javax.swing.JTextArea jRepresentaçãoPerfilFormação;
    private javax.swing.JButton jSair;
    private javax.swing.JButton jSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jSistemaAvaliacaoProcessoEnsino;
    private javax.swing.JTextArea jSistemaAvaliacaoProjetoCurso;
    private javax.swing.JTextField jTrabalhoConclusaoCurso;
    // End of variables declaration//GEN-END:variables
}
