/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.SimulacaoCategoriaAdmAcademicaDao;
import dao.SimulacaoCategoriaPerfilDocentesDao;
import dao.SimulacaoCategoriaPpcDao;
import dao.SimulacaoCategoriaPpcFormacaoDao;
import dao.SimulacaoCondicoesTrabalhoDao;
import dao.SimulacaoMecDao;
import entity.SimulacaoAvaliacaoMec;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class GestaoSimuladorMec extends javax.swing.JDialog {

    /**
     * Creates new form GestaoSimuladorMec
     */
    public GestaoSimuladorMec(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaSimulacoes();
    }
        public void listaSimulacoes(){
            SimulacaoMecDao simulacaoMecDao = new SimulacaoMecDao();
        
        DefaultTableModel modelo = (DefaultTableModel) jTabelaSimulacoes.getModel();
        
        modelo.setNumRows(0);
        for(SimulacaoAvaliacaoMec simulacaoAvaliacaoMec : simulacaoMecDao.getSimulacoes()){
            modelo.addRow(new Object[]{
             simulacaoAvaliacaoMec.getIdentificadorSimulacao()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaSimulacoes = new javax.swing.JTable();
        jNovaSimulacao = new javax.swing.JButton();
        jIniciar = new javax.swing.JButton();
        jExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Simulações Avaliação MEC");

        jTabelaSimulacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador"
            }
        ));
        jTabelaSimulacoes.setToolTipText("");
        jScrollPane1.setViewportView(jTabelaSimulacoes);

        jNovaSimulacao.setText("Nova Simulação");
        jNovaSimulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovaSimulacaoActionPerformed(evt);
            }
        });

        jIniciar.setText("Iniciar");
        jIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciarActionPerformed(evt);
            }
        });

        jExcluir.setText("Excluir");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(156, 156, 156)
                        .addComponent(jNovaSimulacao))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jExcluir)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jNovaSimulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jNovaSimulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovaSimulacaoActionPerformed
        SimuladorAvaliacaoMEC simuladorAvaliacaoMEC = new SimuladorAvaliacaoMEC(new javax.swing.JFrame(), true);
        simuladorAvaliacaoMEC.setVisible(true);
        listaSimulacoes();
    }//GEN-LAST:event_jNovaSimulacaoActionPerformed

    private void jIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarActionPerformed
SimuladorAvaliacaoMEC simuladorAvaliacaoMEC = new SimuladorAvaliacaoMEC(new javax.swing.JFrame(), true);
        int index=-1;
        
        index=jTabelaSimulacoes.getSelectedRow();
      
        if(index!=-1){
        String identificador = jTabelaSimulacoes.getValueAt(jTabelaSimulacoes.getSelectedRow(), 0).toString();
        simuladorAvaliacaoMEC.iniciaSimulacao(identificador);
        
        simuladorAvaliacaoMEC.setVisible(true);
        
        listaSimulacoes();
       }else{
           JOptionPane.showMessageDialog(this, "Selecione uma simulacao");
       }        
    }//GEN-LAST:event_jIniciarActionPerformed

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        int index=-1;
        
        index=jTabelaSimulacoes.getSelectedRow();
      
        if(index!=-1){
            String identificador = jTabelaSimulacoes.getValueAt(jTabelaSimulacoes.getSelectedRow(), 0).toString();
            SimulacaoMecDao simulacaoMecDao = new SimulacaoMecDao();
            int idSimulacao = simulacaoMecDao.getIdSimulacao(identificador);

            if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir a simulação?"
                + "", "Excluir simulacao", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                 if(simulacaoMecDao.Remove(idSimulacao)){
                   
                   SimulacaoCategoriaAdmAcademicaDao sCAA = new SimulacaoCategoriaAdmAcademicaDao();
                   sCAA.Remove(idSimulacao);
                   
                   SimulacaoCategoriaPerfilDocentesDao  sCPD = new SimulacaoCategoriaPerfilDocentesDao();
                   sCPD.Remove(idSimulacao);
                   
                   SimulacaoCategoriaPpcDao sCP = new SimulacaoCategoriaPpcDao();
                   sCP.Remove(idSimulacao);
                   
                   SimulacaoCategoriaPpcFormacaoDao sCPF = new SimulacaoCategoriaPpcFormacaoDao();
                   sCPF.Remove(idSimulacao);
                   
                   SimulacaoCondicoesTrabalhoDao sCT = new SimulacaoCondicoesTrabalhoDao();
                   sCT.Remove(idSimulacao);

                    
                    JOptionPane.showMessageDialog(this, "Simulação removida com sucesso!");

                    listaSimulacoes();
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao remover simulação.");
                }
            }
       }else{
           JOptionPane.showMessageDialog(this, "Selecione uma simulação para remover!");
       }

    }//GEN-LAST:event_jExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoSimuladorMec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoSimuladorMec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoSimuladorMec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoSimuladorMec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestaoSimuladorMec dialog = new GestaoSimuladorMec(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExcluir;
    private javax.swing.JButton jIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jNovaSimulacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaSimulacoes;
    // End of variables declaration//GEN-END:variables
}
